blog/urls.py
from django.conf.urls import url
from .views import get_posts, post_detail, create_or_edit_post, get_posts_by_tag, delete_comment

urlpatterns = [
    url(r'^$', get_posts, name='get_posts'),
    url(r'^tag/(?P<tag>.*)/$', get_posts_by_tag, name='get_posts_by_tag'),
    url(r'^(?P<pk>\d+)/$', post_detail, name='post_detail'),
    url(r'^new/$', create_or_edit_post, name='new_post'),
    url(r'^(?P<pk>\d+)/edit/$', create_or_edit_post, name='edit_post'),
    url(r'^(?P<pk>\d+)/review/(?P<rk>\d+)$', delete_comment, name='delete_comment'),
    ]

facevalue/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home.views import index
from accounts import urls as accounts_urls
from products import urls as urls_products
from cart import urls as urls_cart
from search import urls as urls_search
from checkout import urls as urls_checkout
from blog import urls as urls_blog
from django.views import static
from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^products/', include(urls_products)),
    url(r'^cart/', include(urls_cart)),
    url(r'^search/', include(urls_search)),
    url(r'^checkout/', include(urls_checkout)),
    url(r'^blog/', include(urls_blog)),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': MEDIA_ROOT})
]

products/urls.py
from django.conf.urls import url
from .views import (all_products, face_products, body_products, product_detail,
                    cleanser_products, exfoliator_products, serum_products,
                    moisturiser_products, sunscreen_products, toner_products,
                    masks_products, eye_products, chemical_products,
                    delete_review)

urlpatterns = [
    url(r'^$', all_products, name='products'),
    url(r'^(?P<pk>\d+)/$', product_detail, name='product_detail'),
    url(r'^(?P<pk>\d+)/review/(?P<rk>\d+)$', delete_review, name='delete_review'),
    url(r'^face', face_products, name='face_products'),
    url(r'^body', body_products, name='body_products'),
    url(r'^cleanser', cleanser_products, name='cleanser_products'),
    url(r'^exfoliator', exfoliator_products, name='exfoliator_products'),
    url(r'^serum', serum_products, name='serum_products'),
    url(r'^moisturiser', moisturiser_products, name='moisturiser_products'),
    url(r'^sun', sunscreen_products, name='sunscreen_products'),
    url(r'^toners', toner_products, name='toner_products'),
    url(r'^masks', masks_products, name='masks_products'),
    url(r'^eyes', eye_products, name='eye_products'),
    url(r'^chemical', chemical_products, name='chemical_products'),
]

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


CATEGORY_CHOICES = (
    ('F', 'Face'),
    ('B', 'Body')
)

# Skin Issues - Searchable on the product page
LABEL_CHOICES = (
    ('EC', 'Eczema'),
    ('PS', 'Psoriasis'),
    ('AC', 'Acne'),
    ('RO', 'Rosacea'),
    ('D', 'Dry Skin'),
    ('O', 'Oily Skin'),
    ('S', 'Sensitive'),
    ('TI', 'Tired Skin'),
    ('AG', 'Aging Skin'),
    ('CE', 'Cellulite'),
    ('SC', 'Scarring'),
    ('SU', 'Sun')
)

# Product Types
TYPE_CHOICES = (
    ('C', 'Cleanser'),
    ('EX', 'Exfoliator'),
    ('SE', 'Serum'),
    ('M', 'Moisturiser'),
    ('SU', 'Sunscreen'),
    ('T', 'Toner'),
    ('FM', 'Face Mask'),
    ('E', 'Eye Cream'),
)


class Product(models.Model):
    name = models.CharField(max_length=254, default='')
    price = models.DecimalField(max_digits=6, decimal_places=2)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2,
                                default='F')
    description = models.TextField()
    product_type = models.CharField(choices=TYPE_CHOICES, max_length=2,
                                    default="M")
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.name


class Tag(models.Model):
    product = models.ForeignKey(Product, related_name="tags",
                                related_query_name="tag", null=True)
    value = models.CharField(choices=LABEL_CHOICES, max_length=2)


class Review(models.Model):
    title = models.CharField(max_length=254, default='')
    body = models.TextField()
    score = models.IntegerField()
    approved = models.BooleanField(default=False)
    published_date = models.DateTimeField(blank=True, null=True,
                                          default=timezone.now)
    product = models.ForeignKey(Product, related_name="reviews",
                                on_delete=models.CASCADE,
                                related_query_name="review", null=True)
    user = models.ForeignKey(User, related_name="reviews",
                             on_delete=models.CASCADE,
                             related_query_name="review", null=True)
    
    class Meta:
        ordering = ['-published_date']

products/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('title', 'body', 'score')
        widgets = {'score': forms.HiddenInput()}

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib import messages
from .models import Product, Review
from accounts.models import Favourite
from .forms import ReviewForm
import operator
from django.db.models import Q
from functools import reduce
from django.db.models import Avg


ITEMS_PER_PAGE = 12


def all_products(request):
    filter_keys = [*request.GET]
    if 'page' in filter_keys:
        filter_keys.remove('page')

    if len(filter_keys) > 0:
        products = Product.objects.filter(
            reduce(operator.or_, (Q(tag__value=x)for x in filter_keys))).distinct()

    else:
        products = Product.objects.all()

    paginator = Paginator(products, ITEMS_PER_PAGE)

    page = request.GET.get('page')

    # If there is no page parameter in URL, set page to 1

    if(page is None):
        page = 1

    products = paginator.page(page)

    return render(request, "products.html", {"products": products})


def face_products(request):
    products = Product.objects.all().filter(category='F')

    filter_keys = [*request.GET]
    if 'page' in filter_keys:
        filter_keys.remove('page')

    if len(filter_keys) > 0:
        products = products.filter(
            reduce(operator.or_, (Q(tag__value=x)for x in filter_keys))).distinct()

    paginator = Paginator(products, ITEMS_PER_PAGE)

    page = request.GET.get('page')

    # If there is no page parameter in URL, set page to 1

    if(page is None):
        page = 1

    products = paginator.page(page)
    return render(request, "products.html", {"products": products})


def body_products(request):
    products = Product.objects.all().filter(category='B')

    filter_keys = [*request.GET]
    if 'page' in filter_keys:
        filter_keys.remove('page')

    if len(filter_keys) > 0:
        products = products.filter(
            reduce(operator.or_, (Q(tag__value=x)for x in filter_keys))).distinct()

    paginator = Paginator(products, ITEMS_PER_PAGE)

    page = request.GET.get('page')

    # If there is no page parameter in URL, set page to 1

    if(page is None):
        page = 1

    products = paginator.page(page)
    return render(request, "products.html", {"products": products})


def product_detail(request, pk):
    """
    Create a view that returns a single
    Product object based on the product ID (pk) and
    render it to the 'productdetail.html' template.
    Or return a 404 error if the post is
    not found. User can add a review too
    """
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        if not request.user.is_authenticated:
            return redirect('login')

        else:
            form = ReviewForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.user = request.user
                review.product = product
                review.save()
                messages.success(request, "Thanks for your review, it has been sent for approval!")

            return redirect(product_detail, product.pk)

    else:
        form = ReviewForm()
        review_count = product.reviews.filter(approved=True).count()
        sum = 0 
        avg = 0 
        if review_count > 0:
            for score in product.reviews.filter(approved=True).values("score"):
                sum += score["score"]
            avg = sum / review_count 

        is_favourite = False
        if request.user.is_authenticated:
            user = request.user 
            if Favourite.objects.filter(user=user, product=product).count() > 0:
                is_favourite = True
        return render(request, "productdetail.html", {'product': product,
                                                      'form': form,
                                                      'is_favourite': is_favourite,
                                                      'score': avg,
                                                      'review_count': review_count})


def delete_review(request, pk, rk):
    if request.user.is_authenticated:
        user = request.user 
        review = get_object_or_404(Review, pk=rk)
        review.delete()
        messages.success(request, "Your review is deleted.")
    
    return redirect(product_detail, pk)
   

# View for Product Types

def cleanser_products(request):
    products = Product.objects.all().filter(product_type='C')
    paginator = Paginator(products, ITEMS_PER_PAGE)

    page = request.GET.get('page')

    # If there is no page parameter in URL, set page to 1

    if(page is None):
        page = 1

    products = paginator.page(page)
    return render(request, "products.html", {"products": products})


def exfoliator_products(request):
    products = Product.objects.all().filter(product_type='EX')
    paginator = Paginator(products, ITEMS_PER_PAGE)

    page = request.GET.get('page')

    # If there is no page parameter in URL, set page to 1

    if(page is None):
        page = 1

    products = paginator.page(page)
    return render(request, "products.html", {"products": products})


def serum_products(request):
    products = Product.objects.all().filter(product_type='SE')
    paginator = Paginator(products, ITEMS_PER_PAGE)

    page = request.GET.get('page')

    # If there is no page parameter in URL, set page to 1

    if(page is None):
        page = 1

    products = paginator.page(page)
    return render(request, "products.html", {"products": products})


def moisturiser_products(request):
    products = Product.objects.all().filter(product_type='M')
    paginator = Paginator(products, ITEMS_PER_PAGE)

    page = request.GET.get('page')

    # If there is no page parameter in URL, set page to 1

    if(page is None):
        page = 1

    products = paginator.page(page)
    return render(request, "products.html", {"products": products})


def sunscreen_products(request):
    products = Product.objects.all().filter(product_type='SU')
    paginator = Paginator(products, ITEMS_PER_PAGE)

    page = request.GET.get('page')

    # If there is no page parameter in URL, set page to 1

    if(page is None):
        page = 1

    products = paginator.page(page)
    return render(request, "products.html", {"products": products})


def toner_products(request):
    products = Product.objects.all().filter(product_type='T')
    paginator = Paginator(products, ITEMS_PER_PAGE)

    page = request.GET.get('page')

    # If there is no page parameter in URL, set page to 1

    if(page is None):
        page = 1

    products = paginator.page(page)
    return render(request, "products.html", {"products": products})


def masks_products(request):
    products = Product.objects.all().filter(product_type='FM')
    paginator = Paginator(products, ITEMS_PER_PAGE)

    page = request.GET.get('page')

    # If there is no page parameter in URL, set page to 1

    if(page is None):
        page = 1

    products = paginator.page(page)
    return render(request, "products.html", {"products": products})


def eye_products(request):
    products = Product.objects.all().filter(product_type='E')
    paginator = Paginator(products, ITEMS_PER_PAGE)

    page = request.GET.get('page')

    # If there is no page parameter in URL, set page to 1

    if(page is None):
        page = 1

    products = paginator.page(page)
    return render(request, "products.html", {"products": products})


def chemical_products(request):
    products = Product.objects.all().filter(product_type='CH')
    paginator = Paginator(products, ITEMS_PER_PAGE)

    page = request.GET.get('page')

    # If there is no page parameter in URL, set page to 1

    if(page is None):
        page = 1

    products = paginator.page(page)
    return render(request, "products.html", {"products": products})

products/templates/productdetail.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load bootstrap_tags %}

{% block content %}

<!-- Product Tag -->
<div class="container product-detail-container">
	{% for tag in product.tags.all %}
	<p class="post-category text-white bg-secondary mb-3">{{tag.get_value_display}}</p>
	{% endfor %}
<!-- Product Details with Image -->
	<div class="row">
		<div class="col-12 col-md-8 product-detail-img img-fluid" style="background-image: url('{{ MEDIA_URL }}{{ product.image }}')"></div>
        <div class="product-detail-sm-img d-none d-sm-block d-md-none d-block d-sm-none" style="background-image: url('{{ MEDIA_URL }}{{ product.image }}')"></div>
		<div class="col-12 col-md-4">
			<h4 class="my-3">{{product.name}}</h4>
			<hr>
			<h5 class="my-3 price">Price:
				<span>€{{ product.price }}</span></h5>
			<hr>
            <div class="rating my-3">
            <div class="product-rating"></div>
				{% if review_count == 0 %}
				<div class="my-3">No reviews</div>
				{% else %}
				<div class="my-3"><a href="#review_id">Reviews: {{ review_count }}</a></div>
				{% endif %}
			</div>
			<form method="post" action="{% url 'add_to_cart' product.id %}">
				{% csrf_token %}
				<div class="input-group">
					<input name="quantity" type="number" min="1" max="999" class="form-control" placeholder="Quantity" value="1">
					<span class="input-group-btn">
                            <button class="btn btn-secondary" type="submit">Add</button>
                        </span>
				</div>
			</form>
            {% if user.is_authenticated %}
                {% if is_favourite %}
			<div class="favourite-icon"><a href="{% url 'favourite_product' product.id %}"><i class="fas fa-heart"></i></a></div>
                {% else %}
			<div class="favourite-icon"><a href="{% url 'favourite_product' product.id %}"><i class="far fa-heart"></i></a></div>
            {% endif %}
            {% endif %}
		</div>
	</div>
</div>
<br>
<br>
<!-- Product Description -->
<div class = "col-12 d-flex justify-content-center product-description">{{ product.description }}</div>
<br> 
<hr>
<section id="review_id">
<!-- Review Form -->
<div class="heading_comments_reviews">Reviews on {{product.name}}</div>
<br>
{% if user.is_authenticated %}
<form method="POST" id="account-form">
	{% csrf_token %}
	{{ form | as_bootstrap }}
    <div id="score_input"></div>
	<button type="submit" id="review_submit" class="btn review-btn" disabled>Submit Review</button>
</form>
<!-- If not logged in, tell User to sign in to post a review -->
{% else %}
<br>
<div class="log-in-here"><b><a href="{% url 'login' %}">Sign in here</a></b> to post your own review</div>
<br>
{% endif %}

<!-- If no reviews, say no reviews yet -->
{% if review_count == 0 %}
<hr>
<div class="my-3 d-flex justify-content-center">This product hasn't been reviewed yet!</div>
<hr>
{% endif %}

<!-- If the review has been approved by the Admin, display -->
{% for review in product.reviews.all %}
{% if review.approved %}
<div class="review" style="padding: 10px;">
	<div class="font-weight-bold">
		{{review.title|capfirst}}
		<p class=" text-muted font-weight-normal">
			{{review.user.username}} - {{ review.published_date }}
		</p>
	</div>
	{{ review.body | linebreaks }}
    <div class="user_review_score" data-score="{{review.score}}"></div>
    {% if user == review.user %}
    <button class="btn btn-secondary review-btn" type="submit"><a href ="{% url 'delete_review' product.id review.id %}">Delete Review</a></button>
    {% endif %} 
</div>
<hr>
{% endif %}
{% endfor %}
</section>
{% endblock %}

<!-- JS for Star Ratings, look in README for code credit -->
{% block footer_js %}
<script>
$(document).ready(function(){
    $(".product-rating").starRating({
        starSize: 20,
        initialRating: {{score}},
        readOnly: true,
        useGradient: false,
        activeColor: '#6c757d'
    });
    $("#score_input").starRating({
        starSize: 25,
        initialRating: 0,
        readOnly: false,
        useGradient: false,
        activeColor: '#fff7ff',
        callback: function(rating, $EL){
            $("#id_score").val(rating);
            $("#review_submit").prop('disabled', false)
        },
        useFullStars: true,
        disableAfterRate: false,
        ratedColor: '#00000',
        hoverColor:'#6c757d' 
    });
    $(".product-rating").starRating({
        starSize: 20,
        initialRating: {{score}},
        readOnly: true,
        useGradient: false,
        activeColor: '#6c757d'
    });
    $(".user_review_score").each(function(){
        let score = $(this).data("score");
        $(this).starRating({
            starSize: 20,
            initialRating: score,
            readOnly: true,
            useGradient: false,
            activeColor: '#6c757d'
        });
    })
});
</script>
{% endblock %}

products/templates/products.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block title %}|Products{% endblock %}
{% block content %}

<!-- Search Bar on smaller devices -->
<div class="product_search 	d-block d-sm-none">
	<form class="form-inline" action="{% url 'search' %}" method="get">
		<input class="form-control mr-sm-2" type="text" name="q" placeholder="Search Products" aria-label="Search">
		<button class="btn btn-outline-secondary my-2 my-sm-0 accounts-btn" type="submit">Search</button>
	</form>
</div>

<!-- Tab for Face, Body and All  -->
<div class="tab-wrapper">
	<div class="category_tabs" id="cat-tab">
		<ul>
			<li class="placeholder">
				<a data-type="all" href="{% url 'products' %}">All</a>
			</li>
			<li class="filter"><a href="{% url 'products' %}" class="selected" data-type="all" id="all_products_filter">All</a></li>
			<li class="filter" data-filter=".color-1"><a href="{% url 'face_products' %}" data-type="color-1"
					id="face_products_filter">Face</a>
			</li>
			<li class="filter" data-filter=".color-2"><a href="{% url 'body_products' %}" data-type="color-2"
					id="body_products_filter">Body</a>
			</li>
		</ul>
	</div>
</div>

<!-- Filter Dropdown  -->
<div class="row">
	<div class="col-12 filter-col">
		<div class="button-group">
			<button type="button" class="btn btn-default btn-sm dropdown-toggle tag-dropdown" data-toggle="dropdown"><i class="fas fa-filter"></i></button>
			<ul class="dropdown-menu filter-tag-menu">
				<form method="GET">
                	<li><a class="medium" data-value="Acne"
							tabIndex="-1"><input type="checkbox" name="AC"/>&nbsp; Acne</a></li>
					<li><a class="medium" data-value="Aging"
							tabIndex="-1"><input type="checkbox" name="AG"/>&nbsp; Aging</a></li>
					<li><a class="medium" data-value="Cellulite"
							tabIndex="-1"><input type="checkbox" name="CE"/>&nbsp; Cellulite</a></li>
					<li><a class="medium" data-value="Dry Skin"
							tabIndex="-1"><input type="checkbox" name="D"/>&nbsp; Dry Skin</a></li>
					<li><a class="medium" data-value="Eczema"
							tabIndex="-1"><input type="checkbox" name="EC"/>&nbsp; Eczema</a></li>
					<li><a class="medium" data-value="Oily"
							tabIndex="-1"><input type="checkbox" name="O"/>&nbsp; Oily</a></li>
					<li><a class="medium" data-value="Psoriasis"
							tabIndex="-1"><input type="checkbox" name="PS"/>&nbsp; Psoriasis</a></li>
					<li><a class="medium" data-value="Rosacea"
							tabIndex="-1"><input type="checkbox" name="RO"/>&nbsp; Rosacea</a></li>
					<li><a class="medium" data-value="Scarring"
							tabIndex="-1"><input type="checkbox" name="SC"/>&nbsp; Scarring</a></li>
					<li><a class="medium" data-value="Sensitive Skin"
							tabIndex="-1"><input type="checkbox" name="S"/>&nbsp; Sensitive Skin</a></li>
					<li><a class="medium" data-value="Sun"
							tabIndex="-1"><input type="checkbox" name="SU"/>&nbsp; Sun</a>
					</li>
					<li><a class="medium" data-value="Tired Skin"
							tabIndex="-1"><input type="checkbox" name="TI"/>&nbsp; Tired Skin</a></li>
					<button class="btn btn-secondary tag-filter-btn" type="submit">Filter</button>
                    <br>
                    <p><button class="btn btn-secondary tag-filter-btn" type="submit"><a href="{% url 'products' %}">Clear</a></button></p>
				</form>
			</ul>
		</div>
	</div>
</div>

<!-- Products  -->
<div class="row row-flex products-row">
	{% for product in products %}
	<div class="col-xs-10 col-xs-offset-1 col-sm-offset-0 col-sm-6 col-md-4 product-card card"><a href="{% url 'product_detail' product.id %}">
		<div class="card-body">
			<div class="product" style="background-image: url('{{ MEDIA_URL }}{{ product.image }}')"></div>
            {% for tag in product.tags.all %}
			<span class="post-category text-white bg-danger mb-3">{{ tag.get_value_display }}</span>
            {% endfor %}
			<h4><a href="{% url 'product_detail' product.id %}">{{ product.name }}</a></h4>
			<p class="product-description">{{ product.description|truncatewords:10  }}</p>
			<p>€{{ product.price }}</p>

			<form method="post" action="{% url 'add_to_cart' product.id %}">
				{% csrf_token %}
				<div class="input-group quantity_group col-lg-6 col-10 float-right">
					<input name="quantity" type="number" min="1" max="999" class="form-control" placeholder="Quantity" value="1">
					<span class="input-group-btn">
                            <button class="btn btn-secondary" type="submit" >Add</button>
                        </span>
				</div>
			</form>
		</div>
        </a>
	</div>
	{% endfor %}
</div>

<!-- Pagination -->
<div class="pagination">
	{% if products.has_previous %}
	<a class="pagination-action pagination-class" href="?page=1" id="page_previous"><i class="fas fa-angle-left"></i></a>
	<a class="pagination-action pagination-class" href="?page={{ products.previous_page_number }}"
		id="page_first"><i class="fas fa-angle-double-left"></i></a>
	{% endif %}

	{% for num in products.paginator.page_range %}
	{% if products.number == num %}
	<span class="pagination-number pagination-current">{{num}}</span>
	{% elif num > products.number|add:'-3' and num < products.number|add:'3' %}
	<a class="pagination-number pagination-class" href="?page={{num}}">{{num}}</a>
	{% endif %}
	{% endfor %}

	{% if products.has_next %}
	<a class="pagination-action pagination-class" href="?page={{ products.next_page_number }}"
		id="page_next"><i class="fas fa-angle-right"></i></a>
	<a class="pagination-action pagination-class" href="?page={{ products.paginator.num_pages }}"
		id="page_last"><i class="fas fa-angle-double-right"></i></a>
	{% endif %}
</div>

{% endblock %}

{% block footer_js %}
<script>
$(document).ready(function(){
    let quantity_group = $('.quantity_group');
    quantity_group.each(function(){
        let input = $(this).find('input');
        let button = $(this).find('button');
        input.change(function(){
            if ($(this).val() != "" && $(this).val() > 0){
                $(button).prop('disabled', false);
            }
            else {
                $(button).prop('disabled', true);
            }
        });
    });
});
</script>
{% endblock %}